stages:
  - test
  - build

run_tests:
  stage: test
  image: python:3.9-slim
  services:
    - name: seleniarm/standalone-chromium:latest
      alias: selenium-server
  before_script:
    - pip3 install -r requirements.txt
  script:
    - python -m pytest -v tests/frontend_tests/admin_page_test.py

build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    IMAGE_NAME: 712162196214.dkr.ecr.eu-north-1.amazonaws.com/my-app
  before_script:
      # aws ecr get-login-password --region=eu-north-1
    - docker login -u AWS -p $REGISTRY_TOKEN 712162196214.dkr.ecr.eu-north-1.amazonaws.com
  script:
    - docker build -t $IMAGE_NAME:community-image-1.0 .
    - docker push $IMAGE_NAME:community-image-1.0
