version: '3'
services:
  hw-community-qa:
    build:
      context: .
      dockerfile: Dockerfile

  selenium-server:
    image: seleniarm/standalone-chromium:latest
    ports:
      - 4444:4444

  allure-server:
    image: kochetkovma/allure-server:latest
    ports:
      - 8081:8081
