version: '3'
services:
  selenium-server:
    image: seleniarm/standalone-chromium:latest
    ports:
      - 4444:4444
    networks:
      - my-network-ink

  inktech-qa:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - my-network-ink

networks:
  my-network-ink:
